### ISSUE TITLE
jobclient init fails with gnumake 4.4 and make --jobserver-style=fifo

### ISSUE THREAD

**Issue by milahu** [milahu/gnumake-tokenpool#5]
currently, the jobclient fails to parse MAKEFLAGS like `-j2 --jobserver-auth=fifo:/tmp/asdf`

```
$ ./py/test/test.sh 
+ make -j2
python3 test.py "jobserver on"
debug jobclient.py 781944 2023-12-24 11:01:16.407: init: MAKEFLAGS:  -j2 --jobserver-auth=fifo:/tmp/GMfifo781943
debug jobclient.py 781944 2023-12-24 11:01:16.410: init: fdRead = None, fdWrite = None, maxJobs = 2, maxLoad = None
debug jobclient.py 781944 2023-12-24 11:01:16.410: init failed: no fds
```

`make --jobserver-style=fifo` is the default since gnumake 4.4

quickfix: `make --jobserver-style=pipe`

[gnumake docs](https://www.gnu.org/software/make/manual/html_node/Options-Summary.html#index-_002d_002djobserver_002dstyle)

> --jobserver-style=[style]
>
> Chooses the style of jobserver to use. This option only has effect if parallel builds are enabled (see [Parallel Execution](https://www.gnu.org/software/make/manual/html_node/Parallel.html)). On POSIX systems style can be one of fifo (the default) or pipe. On Windows the only acceptable style is sem (the default). This option is useful if you need to use an older versions of GNU make, or a different tool that requires a specific jobserver style.

see also

- https://github.com/spack/spack/issues/33014
- https://github.com/rust-lang/jobserver-rs/issues/47

**Comment by milahu** [comment]
jobserver-style fifo should work now in [javascript](https://github.com/milahu/gnumake-tokenpool/commit/acd3c184ccfe5ad58c97014083f58be9db8dcb1c) and [python](https://github.com/milahu/gnumake-tokenpool/commit/bcc75be7bef0c98f6ed9ceb46379caff5eb59841)

**Comment by mkoeppe** [comment]
Great. I'll set up a GH Actions workflow that will publish to PyPI when a py/... tag is pushed

**Comment by mkoeppe** [comment]
https://pypi.org/project/gnumake-tokenpool/0.0.6/ (created by the new GH Actions workflow)

**Comment by milahu** [comment]
closing as "should be fixed"

> jobserver-style fifo should work now in [javascript](https://github.com/milahu/gnumake-tokenpool/commit/acd3c184ccfe5ad58c97014083f58be9db8dcb1c) and [python](https://github.com/milahu/gnumake-tokenpool/commit/bcc75be7bef0c98f6ed9ceb46379caff5eb59841)
